# Generated by Django 3.2.7 on 2021-09-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='status_isCompleted',
        ),
    ]
