# Generated by Django 3.2.7 on 2021-09-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='text',
        ),
    ]
