# Generated by Django 3.2.7 on 2021-09-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status_isCompleted',
            new_name='isCompleted',
        ),
    ]
