# Generated by Django 3.2.7 on 2021-09-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='task',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
