# Generated by Django 3.2.7 on 2021-09-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210908_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isCompleted',
            new_name='is_completed',
        ),
    ]
