# Generated by Django 3.2.7 on 2021-09-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='work_time',
        ),
    ]
