# Generated by Django 3.2.7 on 2021-09-08 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
