# Generated by Django 3.2.7 on 2021-09-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0002_auto_20210908_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
